In [2]:
import pandas as pd

LIMIT_BAL: This feature represents the credit limit assigned to the individual's credit card. It indicates the maximum amount of credit the person can utilize.

SEX: This feature represents the gender of the credit card holder. While gender itself may not directly impact credit card fault detection, it can be considered as a demographic factor that might have some influence on creditworthiness.

EDUCATION: This feature indicates the educational background of the credit card holder. It can provide insights into the person's level of education, which might indirectly correlate with their financial stability and ability to manage credit.

MARRIAGE: This feature represents the marital status of the credit card holder. Similar to gender, marital status can be a demographic factor that could potentially impact credit card fault detection.

AGE: This feature denotes the age of the credit card holder. Age can be an important factor in assessing creditworthiness as it often correlates with financial responsibility and stability.

PAY_0, PAY_2, PAY_3, PAY_4, PAY_5, PAY_6: These features represent the repayment status of the credit card for the past six months. The values indicate the payment status (e.g., -1 represents payment delay for one month, 0 represents payment on time, 1 represents payment delay for two months, and so on). These features are crucial in determining the payment behavior of the individual over time.

BILL_AMT1, BILL_AMT2, BILL_AMT3, BILL_AMT4, BILL_AMT5, BILL_AMT6: These features represent the amount of bill statement for the respective months. They provide information about the outstanding balance on the credit card at specific points in time.

PAY_AMT1, PAY_AMT2, PAY_AMT3, PAY_AMT4, PAY_AMT5, PAY_AMT6: These features represent the amount of payment made by the credit card holder for the respective months. They indicate the actual payments made to reduce the outstanding balance.

default payment next month: This is the target variable or the dependent variable that indicates whether the credit card holder defaulted on their payment in the following month (1 for default, 0 for no default). This is the variable that the credit card fault detection model aims to predict.

In [3]:
data=pd.read_csv(r"D:\Projects\Credit Card Fault Detection\upload_data_to_database\data\CreditCardFraud_28011964_120214.csv")

In [3]:
data.head()

,LIMIT_BAL,SEX,EDUCATION,MARRIAGE,AGE,PAY_0,PAY_2,PAY_3,PAY_4,PAY_5,...,BILL_AMT4,BILL_AMT5,BILL_AMT6,PAY_AMT1,PAY_AMT2,PAY_AMT3,PAY_AMT4,PAY_AMT5,PAY_AMT6,default payment next month
0,50000,1,2,1,57,-1,0,-1,0,0,...,20940,19146,19131,2000,36681,10000,9000,689,679,0
1,50000,1,1,2,37,0,0,0,0,0,...,19394,19619,20024,2500,1815,657,1000,1000,800,0
2,500000,1,1,2,29,0,0,0,0,0,...,542653,483003,473944,55000,40000,38000,20239,13750,13770,0
3,100000,2,2,2,23,0,-1,-1,0,0,...,221,-159,567,380,601,0,581,1687,1542,0
4,140000,2,3,1,28,0,0,2,0,0,...,12211,11793,3719,3329,0,432,1000,1000,1000,0

In [4]:
data.columns

Index(['LIMIT_BAL', 'SEX', 'EDUCATION', 'MARRIAGE', 'AGE', 'PAY_0', 'PAY_2',
       'PAY_3', 'PAY_4', 'PAY_5', 'PAY_6', 'BILL_AMT1', 'BILL_AMT2',
       'BILL_AMT3', 'BILL_AMT4', 'BILL_AMT5', 'BILL_AMT6', 'PAY_AMT1',
       'PAY_AMT2', 'PAY_AMT3', 'PAY_AMT4', 'PAY_AMT5', 'PAY_AMT6',
       'default payment next month'],
      dtype='object')

In [5]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1001 entries, 0 to 1000
Data columns (total 24 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   LIMIT_BAL                   1001 non-null   int64
 1   SEX                         1001 non-null   int64
 2   EDUCATION                   1001 non-null   int64
 3   MARRIAGE                    1001 non-null   int64
 4   AGE                         1001 non-null   int64
 5   PAY_0                       1001 non-null   int64
 6   PAY_2                       1001 non-null   int64
 7   PAY_3                       1001 non-null   int64
 8   PAY_4                       1001 non-null   int64
 9   PAY_5                       1001 non-null   int64
 10  PAY_6                       1001 non-null   int64
 11  BILL_AMT1                   1001 non-null   int64
 12  BILL_AMT2                   1001 non-null   int64
 13  BILL_AMT3                   1001 non-null   int64
 14  BILL_AMT4                   1001 non-null   int64
 15  BILL_AMT5                   1001 non-null   int64
 16  BILL_AMT6                   1001 non-null   int64
 17  PAY_AMT1                    1001 non-null   int64
 18  PAY_AMT2                    1001 non-null   int64
 19  PAY_AMT3                    1001 non-null   int64
 20  PAY_AMT4                    1001 non-null   int64
 21  PAY_AMT5                    1001 non-null   int64
 22  PAY_AMT6                    1001 non-null   int64
 23  default payment next month  1001 non-null   int64
dtypes: int64(24)
memory usage: 187.8 KB

In [6]:
data.describe()

,LIMIT_BAL,SEX,EDUCATION,MARRIAGE,AGE,PAY_0,PAY_2,PAY_3,PAY_4,PAY_5,...,BILL_AMT4,BILL_AMT5,BILL_AMT6,PAY_AMT1,PAY_AMT2,PAY_AMT3,PAY_AMT4,PAY_AMT5,PAY_AMT6,default payment next month
count,1001.000000,1001.000000,1001.000000,1001.000000,1001.000000,1001.000000,1001.000000,1001.000000,1001.000000,1001.000000,...,1001.000000,1001.000000,1001.000000,1001.000000,1001.000000,1001.000000,1001.000000,1001.000000,1001.000000,1001.000000
mean,167532.467532,1.589411,1.776224,1.604396,34.945055,-0.004995,-0.161838,-0.164835,-0.283716,-0.283716,...,40748.408591,39078.666334,38012.011988,5382.339660,5051.400599,4176.149850,4671.488511,5331.049950,5090.704296,0.213786
std,130587.921320,0.492187,0.750916,0.532298,9.219760,1.173446,1.228732,1.262459,1.184662,1.170224,...,68206.929510,63108.238729,63074.415024,12180.755275,15626.153184,10514.647502,13269.943983,16812.536877,23658.888052,0.410183
min,10000.000000,1.000000,1.000000,0.000000,21.000000,-2.000000,-2.000000,-2.000000,-2.000000,-2.000000,...,-3684.000000,-28335.000000,-339603.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,50000.000000,1.000000,1.000000,1.000000,28.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,...,1423.000000,1206.000000,830.000000,1000.000000,390.000000,228.000000,148.000000,189.000000,0.000000,0.000000
50%,140000.000000,2.000000,2.000000,2.000000,33.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,17710.000000,17580.000000,15846.000000,2184.000000,1710.000000,1206.000000,1398.000000,1306.000000,1250.000000,0.000000
75%,240000.000000,2.000000,2.000000,2.000000,41.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,48851.000000,46404.000000,46557.000000,5090.000000,4500.000000,3720.000000,4000.000000,3745.000000,3784.000000,0.000000
max,700000.000000,2.000000,6.000000,3.000000,75.000000,8.000000,7.000000,7.000000,7.000000,7.000000,...,628699.000000,484612.000000,473944.000000,199646.000000,285138.000000,133657.000000,188840.000000,195599.000000,528666.000000,1.000000

In [7]:
!pip install pandas-profiling

Requirement already satisfied: pandas-profiling in d:\projects\credit card fault detection\venv\lib\site-packages (3.6.6)
Requirement already satisfied: ydata-profiling in d:\projects\credit card fault detection\venv\lib\site-packages (from pandas-profiling) (4.5.1)
Requirement already satisfied: scipy<1.12,>=1.4.1 in d:\projects\credit card fault detection\venv\lib\site-packages (from ydata-profiling->pandas-profiling) (1.10.1)
Requirement already satisfied: pandas!=1.4.0,<2.1,>1.1 in d:\projects\credit card fault detection\venv\lib\site-packages (from ydata-profiling->pandas-profiling) (2.0.3)
Requirement already satisfied: matplotlib<4,>=3.2 in d:\projects\credit card fault detection\venv\lib\site-packages (from ydata-profiling->pandas-profiling) (3.7.2)
Requirement already satisfied: pydantic<2,>=1.8.1 in d:\projects\credit card fault detection\venv\lib\site-packages (from ydata-profiling->pandas-profiling) (1.10.12)
Requirement already satisfied: PyYAML<6.1,>=5.0.0 in d:\projects\credit card fault detection\venv\lib\site-packages (from ydata-profiling->pandas-profiling) (5.4.1)
Requirement already satisfied: jinja2<3.2,>=2.11.1 in d:\projects\credit card fault detection\venv\lib\site-packages (from ydata-profiling->pandas-profiling) (3.1.2)
Requirement already satisfied: visions[type_image_path]==0.7.5 in d:\projects\credit card fault detection\venv\lib\site-packages (from ydata-profiling->pandas-profiling) (0.7.5)
Requirement already satisfied: numpy<1.24,>=1.16.0 in d:\projects\credit card fault detection\venv\lib\site-packages (from ydata-profiling->pandas-profiling) (1.23.5)
Requirement already satisfied: htmlmin==0.1.12 in d:\projects\credit card fault detection\venv\lib\site-packages (from ydata-profiling->pandas-profiling) (0.1.12)
Requirement already satisfied: phik<0.13,>=0.11.1 in d:\projects\credit card fault detection\venv\lib\site-packages (from ydata-profiling->pandas-profiling) (0.12.3)
Requirement already satisfied: requests<3,>=2.24.0 in d:\projects\credit card fault detection\venv\lib\site-packages (from ydata-profiling->pandas-profiling) (2.31.0)
Requirement already satisfied: tqdm<5,>=4.48.2 in d:\projects\credit card fault detection\venv\lib\site-packages (from ydata-profiling->pandas-profiling) (4.66.1)
Requirement already satisfied: seaborn<0.13,>=0.10.1 in d:\projects\credit card fault detection\venv\lib\site-packages (from ydata-profiling->pandas-profiling) (0.12.2)
Requirement already satisfied: multimethod<2,>=1.4 in d:\projects\credit card fault detection\venv\lib\site-packages (from ydata-profiling->pandas-profiling) (1.9.1)
Requirement already satisfied: statsmodels<1,>=0.13.2 in d:\projects\credit card fault detection\venv\lib\site-packages (from ydata-profiling->pandas-profiling) (0.14.0)
Requirement already satisfied: typeguard<3,>=2.13.2 in d:\projects\credit card fault detection\venv\lib\site-packages (from ydata-profiling->pandas-profiling) (2.13.3)
Requirement already satisfied: imagehash==4.3.1 in d:\projects\credit card fault detection\venv\lib\site-packages (from ydata-profiling->pandas-profiling) (4.3.1)
Requirement already satisfied: wordcloud>=1.9.1 in d:\projects\credit card fault detection\venv\lib\site-packages (from ydata-profiling->pandas-profiling) (1.9.2)
Requirement already satisfied: dacite>=1.8 in d:\projects\credit card fault detection\venv\lib\site-packages (from ydata-profiling->pandas-profiling) (1.8.1)
Requirement already satisfied: PyWavelets in d:\projects\credit card fault detection\venv\lib\site-packages (from imagehash==4.3.1->ydata-profiling->pandas-profiling) (1.4.1)
Requirement already satisfied: pillow in d:\projects\credit card fault detection\venv\lib\site-packages (from imagehash==4.3.1->ydata-profiling->pandas-profiling) (10.0.0)
Requirement already satisfied: attrs>=19.3.0 in d:\projects\credit card fault detection\venv\lib\site-packages (from visions[type_image_path]==0.7.5->ydata-profiling->pandas-profiling) (23.1.0)
Requirement already satisfied: networkx>=2.4 in d:\projects\credit card fault detection\venv\lib\site-packages (from visions[type_image_path]==0.7.5->ydata-profiling->pandas-profiling) (3.1)
Requirement already satisfied: tangled-up-in-unicode>=0.0.4 in d:\projects\credit card fault detection\venv\lib\site-packages (from visions[type_image_path]==0.7.5->ydata-profiling->pandas-profiling) (0.2.0)
Requirement already satisfied: MarkupSafe>=2.0 in d:\projects\credit card fault detection\venv\lib\site-packages (from jinja2<3.2,>=2.11.1->ydata-profiling->pandas-profiling) (2.1.3)
Requirement already satisfied: contourpy>=1.0.1 in d:\projects\credit card fault detection\venv\lib\site-packages (from matplotlib<4,>=3.2->ydata-profiling->pandas-profiling) (1.1.0)
Requirement already satisfied: cycler>=0.10 in d:\projects\credit card fault detection\venv\lib\site-packages (from matplotlib<4,>=3.2->ydata-profiling->pandas-profiling) (0.11.0)
Requirement already satisfied: fonttools>=4.22.0 in d:\projects\credit card fault detection\venv\lib\site-packages (from matplotlib<4,>=3.2->ydata-profiling->pandas-profiling) (4.42.1)
Requirement already satisfied: kiwisolver>=1.0.1 in d:\projects\credit card fault detection\venv\lib\site-packages (from matplotlib<4,>=3.2->ydata-profiling->pandas-profiling) (1.4.5)
Requirement already satisfied: packaging>=20.0 in c:\users\ocac\appdata\roaming\python\python38\site-packages (from matplotlib<4,>=3.2->ydata-profiling->pandas-profiling) (23.1)
Requirement already satisfied: pyparsing<3.1,>=2.3.1 in d:\projects\credit card fault detection\venv\lib\site-packages (from matplotlib<4,>=3.2->ydata-profiling->pandas-profiling) (3.0.9)
Requirement already satisfied: python-dateutil>=2.7 in c:\users\ocac\appdata\roaming\python\python38\site-packages (from matplotlib<4,>=3.2->ydata-profiling->pandas-profiling) (2.8.2)
Requirement already satisfied: importlib-resources>=3.2.0 in d:\projects\credit card fault detection\venv\lib\site-packages (from matplotlib<4,>=3.2->ydata-profiling->pandas-profiling) (6.0.1)
Requirement already satisfied: pytz>=2020.1 in d:\projects\credit card fault detection\venv\lib\site-packages (from pandas!=1.4.0,<2.1,>1.1->ydata-profiling->pandas-profiling) (2023.3)
Requirement already satisfied: tzdata>=2022.1 in d:\projects\credit card fault detection\venv\lib\site-packages (from pandas!=1.4.0,<2.1,>1.1->ydata-profiling->pandas-profiling) (2023.3)
Requirement already satisfied: joblib>=0.14.1 in d:\projects\credit card fault detection\venv\lib\site-packages (from phik<0.13,>=0.11.1->ydata-profiling->pandas-profiling) (1.3.2)
Requirement already satisfied: typing-extensions>=4.2.0 in c:\users\ocac\appdata\roaming\python\python38\site-packages (from pydantic<2,>=1.8.1->ydata-profiling->pandas-profiling) (4.7.1)
Requirement already satisfied: charset-normalizer<4,>=2 in d:\projects\credit card fault detection\venv\lib\site-packages (from requests<3,>=2.24.0->ydata-profiling->pandas-profiling) (3.2.0)
Requirement already satisfied: idna<4,>=2.5 in d:\projects\credit card fault detection\venv\lib\site-packages (from requests<3,>=2.24.0->ydata-profiling->pandas-profiling) (3.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in d:\projects\credit card fault detection\venv\lib\site-packages (from requests<3,>=2.24.0->ydata-profiling->pandas-profiling) (1.26.16)
Requirement already satisfied: certifi>=2017.4.17 in d:\projects\credit card fault detection\venv\lib\site-packages (from requests<3,>=2.24.0->ydata-profiling->pandas-profiling) (2023.7.22)
Requirement already satisfied: patsy>=0.5.2 in d:\projects\credit card fault detection\venv\lib\site-packages (from statsmodels<1,>=0.13.2->ydata-profiling->pandas-profiling) (0.5.3)
Requirement already satisfied: colorama in c:\users\ocac\appdata\roaming\python\python38\site-packages (from tqdm<5,>=4.48.2->ydata-profiling->pandas-profiling) (0.4.6)
Requirement already satisfied: zipp>=3.1.0 in c:\users\ocac\appdata\roaming\python\python38\site-packages (from importlib-resources>=3.2.0->matplotlib<4,>=3.2->ydata-profiling->pandas-profiling) (3.16.2)
Requirement already satisfied: six in c:\users\ocac\appdata\roaming\python\python38\site-packages (from patsy>=0.5.2->statsmodels<1,>=0.13.2->ydata-profiling->pandas-profiling) (1.16.0)

In [8]:
from pandas_profiling import ProfileReport

C:\Users\OCAC\AppData\Local\Temp\ipykernel_12160\2274191625.py:1: DeprecationWarning: `import pandas_profiling` is going to be deprecated by April 1st. Please use `import ydata_profiling` instead.
  from pandas_profiling import ProfileReport

In [9]:
profile=ProfileReport(data,title="pandas profiling report")

In [10]:
profile.to_file("report.html")

Summarize dataset:   0%|          | 0/5 [00:00<?, ?it/s]

Generate report structure:   0%|          | 0/1 [00:00<?, ?it/s]

Render HTML:   0%|          | 0/1 [00:00<?, ?it/s]

Export report to file:   0%|          | 0/1 [00:00<?, ?it/s]